[2022-12-05 11:28:20,148] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.getData manual__2022-12-05T11:22:55.948213+00:00 [queued]>
[2022-12-05 11:28:20,161] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.getData manual__2022-12-05T11:22:55.948213+00:00 [queued]>
[2022-12-05 11:28:20,161] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-05 11:28:20,161] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-05 11:28:20,161] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-05 11:28:20,175] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): getData> on 2022-12-05 11:22:55.948213+00:00
[2022-12-05 11:28:20,183] {standard_task_runner.py:52} INFO - Started process 376 to run task
[2022-12-05 11:28:20,189] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'getData', 'manual__2022-12-05T11:22:55.948213+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp8_okzryr', '--error-file', '/tmp/tmpezecnfl4']
[2022-12-05 11:28:20,191] {standard_task_runner.py:77} INFO - Job 7: Subtask getData
[2022-12-05 11:28:20,258] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.getData manual__2022-12-05T11:22:55.948213+00:00 [running]> on host 773d78d86e4f
[2022-12-05 11:28:20,323] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=getData
AIRFLOW_CTX_EXECUTION_DATE=2022-12-05T11:22:55.948213+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-05T11:22:55.948213+00:00
[2022-12-05 11:28:20,446] {python.py:175} INFO - Done. Returned value was: None
[2022-12-05 11:28:20,461] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=getData, execution_date=20221205T112255, start_date=20221205T112820, end_date=20221205T112820
[2022-12-05 11:28:20,524] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-05 11:28:20,575] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
